development:
   adapter: mysql
   database: rubyBlog
   username: root
   password: 
   host: localhost
  
test:
   adapter: mysql
   database: rubyBlog
   username: root
   password: 
   host: localhost
   
production:
   adapter: mysql
   database: rubyBlog
   username: root
   password: 
   host: localhost
